# Generated by Django 4.2.15 on 2024-09-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
