# Generated by Django 4.2.15 on 2024-09-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temps', '0002_alter_temperature_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='time',
            field=models.TimeField(),
        ),
    ]
