# Generated by Django 3.2.19 on 2025-01-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temps', '0006_alter_temperature_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='source',
            field=models.CharField(default='harri', max_length=100),
            preserve_default=False,
        ),
    ]
