# Generated by Django 3.2.25 on 2026-04-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temps', '0007_temperature_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='humidity',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
